version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: organizer-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: organizers-app
    ports:
      - '5432:5432'
